# This workflow builds all the TDD-By-Example projects and runs the tests.

name: TDD-By-Example Test Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: Test Java Chapter 1
      working-directory: java/ch01
      run: mvn clean test
    - name: Test Java Chapter 2
      working-directory: java/ch02
      run: mvn clean test
    - name: Test Java Chapter 3
      working-directory: java/ch03
      run: mvn clean test
    - name: Test Java Chapter 4
      working-directory: java/ch04
      run: mvn clean test
    - name: Test Java Chapter 5
      working-directory: java/ch05
      run: mvn clean test
    - name: Test Java Chapter 6
      working-directory: java/ch06
      run: mvn clean test
    - name: Test Java Chapter 7
      working-directory: java/ch07
      run: mvn clean test
    - name: Test Java Chapter 8
      working-directory: java/ch08
      run: mvn clean test
    - name: Test Java Chapter 9
      working-directory: java/ch09
      run: mvn clean test
    - name: Test Java Chapter 10
      working-directory: java/ch10
      run: mvn clean test
    - name: Test Java Chapter 11
      working-directory: java/ch11
      run: mvn clean test
    - name: Test Java Chapter 12
      working-directory: java/ch12
      run: mvn clean test
    - name: Test Java Chapter 13
      working-directory: java/ch13
      run: mvn clean test
    - name: Test Java Chapter 14
      working-directory: java/ch14
      run: mvn clean test
    - name: Test Java Chapter 15
      working-directory: java/ch15
      run: mvn clean test
    - name: Test Java Chapter 16
      working-directory: java/ch16
      run: mvn clean test
    - name: Test Java Chapter 17 - 01
      working-directory: java/ch17-01-tests
      run: mvn clean test
    - name: Test Java Chapter 17 - 02
      working-directory: java/ch17-02-plus
      run: mvn clean test
    - name: Test Java Chapter 17 - 03
      working-directory: java/ch17-03-decimal
      run: mvn clean test
    - name: Test Java Chapter 17 - 04
      working-directory: java/ch17-04-arithmetic
      run: mvn clean test
  dotnet-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Test .NET Chapter 1
      working-directory: cs/ch01
      run: dotnet test
    - name: Test .NET Chapter 2
      working-directory: cs/ch02
      run: dotnet test
    - name: Test .NET Chapter 3
      working-directory: cs/ch03
      run: dotnet test
    - name: Test .NET Chapter 4
      working-directory: cs/ch04
      run: dotnet test
    - name: Test .NET Chapter 5
      working-directory: cs/ch05
      run: dotnet test
    - name: Test .NET Chapter 6
      working-directory: cs/ch06
      run: dotnet test
    - name: Test .NET Chapter 7
      working-directory: cs/ch07
      run: dotnet test
    - name: Test .NET Chapter 8
      working-directory: cs/ch08
      run: dotnet test
    - name: Test .NET Chapter 9
      working-directory: cs/ch09
      run: dotnet test
    - name: Test .NET Chapter 10
      working-directory: cs/ch10
      run: dotnet test
    - name: Test .NET Chapter 11
      working-directory: cs/ch11
      run: dotnet test
    - name: Test .NET Chapter 12
      working-directory: cs/ch12
      run: dotnet test
    - name: Test .NET Chapter 13
      working-directory: cs/ch13
      run: dotnet test
    - name: Test .NET Chapter 14
      working-directory: cs/ch14
      run: dotnet test
    - name: Test .NET Chapter 15
      working-directory: cs/ch15
      run: dotnet test
    - name: Test .NET Chapter 16
      working-directory: cs/ch16
      run: dotnet test
    - name: Test .NET Chapter 17 - 01
      working-directory: cs/ch17-01-tests
      run: dotnet test
    - name: Test .NET Chapter 17 - 02
      working-directory: cs/ch17-02-plus
      run: dotnet test
    - name: Test .NET Chapter 17 - 03
      working-directory: cs/ch17-03-decimal
      run: dotnet test
    - name: Test .NET Chapter 17 - 04
      working-directory: cs/ch17-04-arithmetic
      run: dotnet test
